/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.miniJava.impl;

import demidov.projects.miniJava.MiniJavaPackage;
import demidov.projects.miniJava.SquareBrackets;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Square Brackets</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SquareBracketsImpl extends ExprImpl implements SquareBrackets
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SquareBracketsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MiniJavaPackage.Literals.SQUARE_BRACKETS;
  }

} //SquareBracketsImpl
