/*
 * generated by Xtext 2.9.1
 */
package demidov.projects.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMiniJavaScopeProvider extends DelegatingScopeProvider {
}
