/*
 * generated by Xtext 2.9.1
 */
package demidov.projects.parser.antlr;

import com.google.inject.Inject;
import demidov.projects.parser.antlr.internal.InternalMiniJavaParser;
import demidov.projects.services.MiniJavaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MiniJavaParser extends AbstractAntlrParser {

	@Inject
	private MiniJavaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMiniJavaParser createParser(XtextTokenStream stream) {
		return new InternalMiniJavaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public MiniJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MiniJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
