/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.miniJava;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link demidov.projects.miniJava.ClassDecl#getName <em>Name</em>}</li>
 *   <li>{@link demidov.projects.miniJava.ClassDecl#getMainMethod <em>Main Method</em>}</li>
 *   <li>{@link demidov.projects.miniJava.ClassDecl#getExtendedClass <em>Extended Class</em>}</li>
 *   <li>{@link demidov.projects.miniJava.ClassDecl#getVarDeclarations <em>Var Declarations</em>}</li>
 *   <li>{@link demidov.projects.miniJava.ClassDecl#getMethodDeclarations <em>Method Declarations</em>}</li>
 * </ul>
 *
 * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl()
 * @model
 * @generated
 */
public interface ClassDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link demidov.projects.miniJava.ClassDecl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Main Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main Method</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Method</em>' containment reference.
   * @see #setMainMethod(MainMethod)
   * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl_MainMethod()
   * @model containment="true"
   * @generated
   */
  MainMethod getMainMethod();

  /**
   * Sets the value of the '{@link demidov.projects.miniJava.ClassDecl#getMainMethod <em>Main Method</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main Method</em>' containment reference.
   * @see #getMainMethod()
   * @generated
   */
  void setMainMethod(MainMethod value);

  /**
   * Returns the value of the '<em><b>Extended Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extended Class</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extended Class</em>' reference.
   * @see #setExtendedClass(ClassDecl)
   * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl_ExtendedClass()
   * @model
   * @generated
   */
  ClassDecl getExtendedClass();

  /**
   * Sets the value of the '{@link demidov.projects.miniJava.ClassDecl#getExtendedClass <em>Extended Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extended Class</em>' reference.
   * @see #getExtendedClass()
   * @generated
   */
  void setExtendedClass(ClassDecl value);

  /**
   * Returns the value of the '<em><b>Var Declarations</b></em>' containment reference list.
   * The list contents are of type {@link demidov.projects.miniJava.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Declarations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Declarations</em>' containment reference list.
   * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl_VarDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getVarDeclarations();

  /**
   * Returns the value of the '<em><b>Method Declarations</b></em>' containment reference list.
   * The list contents are of type {@link demidov.projects.miniJava.Method}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method Declarations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Declarations</em>' containment reference list.
   * @see demidov.projects.miniJava.MiniJavaPackage#getClassDecl_MethodDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<Method> getMethodDeclarations();

} // ClassDecl
