/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.miniJava;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Square Brackets</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see demidov.projects.miniJava.MiniJavaPackage#getSquareBrackets()
 * @model
 * @generated
 */
public interface SquareBrackets extends Expr
{
} // SquareBrackets
