/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.miniJava;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link demidov.projects.miniJava.Variable#getVariableType <em>Variable Type</em>}</li>
 *   <li>{@link demidov.projects.miniJava.Variable#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see demidov.projects.miniJava.MiniJavaPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Type</em>' containment reference.
   * @see #setVariableType(Type)
   * @see demidov.projects.miniJava.MiniJavaPackage#getVariable_VariableType()
   * @model containment="true"
   * @generated
   */
  Type getVariableType();

  /**
   * Sets the value of the '{@link demidov.projects.miniJava.Variable#getVariableType <em>Variable Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Type</em>' containment reference.
   * @see #getVariableType()
   * @generated
   */
  void setVariableType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see demidov.projects.miniJava.MiniJavaPackage#getVariable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link demidov.projects.miniJava.Variable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Variable
