/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.ui.contentassist;

import demidov.projects.ui.contentassist.AbstractMiniJavaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MiniJavaProposalProvider extends AbstractMiniJavaProposalProvider {
}
