/**
 * generated by Xtext 2.9.1
 */
package demidov.projects;

import demidov.projects.AbstractMiniJavaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MiniJavaRuntimeModule extends AbstractMiniJavaRuntimeModule {
}
