/**
 * generated by Xtext 2.9.1
 */
package demidov.projects;

import demidov.projects.MiniJavaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MiniJavaStandaloneSetup extends MiniJavaStandaloneSetupGenerated {
  public static void doSetup() {
    MiniJavaStandaloneSetup _miniJavaStandaloneSetup = new MiniJavaStandaloneSetup();
    _miniJavaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
