/**
 * generated by Xtext 2.9.1
 */
package demidov.projects.ui;

import demidov.projects.ui.AbstractMiniJavaUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MiniJavaUiModule extends AbstractMiniJavaUiModule {
  public MiniJavaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
